- openstack_plugin_common/__init__.py
made warnings from openstack plugin appear only once
> CFY-3060-Security-warning-messages-with-new-requests-version

- system_tests/openstack_handler.py
CFY-3145 - flake8
CFY-3145 - trying to delete volumes in use as well
CFY-3145 - openstack cleanup handler - waiting for volume deletion + avoiding key-pair deletion
> CFY-3145 - not deleting key-pairs

- system_tests/openstack_handler.py
Implementing the idea of "a system test should make sure it removes
the keypairs it created", provide a way for the test to do so.
This changeset introduces three ways to delete keypairs:
- querying by name
- remove all keypairs corresponding to nodes in local_env
- remove all keypairs corresponding to nodes stored in a manager,
querying by deployment_id
> CFY-4607 add an API for removing keypairs for a deployment

- neutron_plugin/port.py
- neutron_plugin/tests/test_port.py
Good enough fix for race condition that is checking in OpenStack API if security group is in port security groups list. If not, update port is called again. Race condition is less probable but still possible.
> Checking for port-SG connection

- cinder_plugin/volume.py
- glance_plugin/__init__.py
- glance_plugin/image.py
- glance_plugin/tests/resources/test-image-start.yaml
- glance_plugin/tests/test.py
- nova_plugin/server.py
- nova_plugin/tests/test_server.py
- openstack_plugin_common/__init__.py
- plugin.yaml
- setup.py
- tox.ini
> Cfy 5395 create image

- neutron_plugin/floatingip.py
- neutron_plugin/network.py
- neutron_plugin/port.py
- neutron_plugin/router.py
- nova_plugin/keypair.py
- nova_plugin/server.py
- openstack_plugin_common/__init__.py
- openstack_plugin_common/tests/openstack_client_tests.py
- plugin.yaml
Use `create_if_missing` property to control conditional creation of resources.
> CFY-5652 Add conditional creation

- keystone_plugin/__init__.py
- keystone_plugin/project.py
- keystone_plugin/tests/test.py
- openstack_plugin_common/__init__.py
- openstack_plugin_common/tests/openstack_client_tests.py
- plugin.yaml
- setup.py
- tox.ini
Add project. 
Assign users to project. 
Add nova, neutron, cinder quotas.
> Cfy 5392 add project

- CHANGELOG.txt
- cinder_plugin/volume.py
- nova_plugin/server.py
- nova_plugin/tests/test_server.py
- openstack_plugin_common/__init__.py
> OPENSTACK-93 Add availability_zone from boot volume if none specified

- nova_plugin/server.py
Server
JIRAs: OPENSTACK-92 OPENSTACK-93
> Still upate boot_device_mapping if availability_zone is specified in

- openstack_plugin_common/__init__.py
- openstack_plugin_common/tests/openstack_client_tests.py
- setup.py
- tox.ini
> Fix order of config merging & region -> region_name change

- nova_plugin/server.py
- plugin.yaml
> Update nova exception handling for new library

- openstack_plugin_common/__init__.py
> Update validation functions for new libraries

- glance_plugin/tests/resources/test-image-start.yaml
- nova_plugin/server.py
- nova_plugin/tests/resources/test-keypair-validation-blueprint.yaml
- nova_plugin/tests/resources/test-server-create-secgroup.yaml
- nova_plugin/tests/resources/test-start-operation-retry-blueprint.yaml
- nova_plugin/tests/test_server.py
- openstack_plugin_common/__init__.py
- setup.py
Add function to get external_id from related nodes
Add function to assign runtime properties before api call
> support attach sec grp in server create

- CHANGELOG.txt
- blueprints/inputs.yaml
- blueprints/router.yaml
- neutron_plugin/router.py
- neutron_plugin/tests/test_router.py
- plugin.yaml
- setup.py
Add router.configure
Add tests
simple version
> OPENSTACK-121

- setup.py
This will only be relevant in the next release.
> Updating Plugins Common Version

- docs/types.rst
- nova_plugin/flavor.py
- nova_plugin/tests/test_flavor.py
- plugin.yaml
Add flavor (create, delete, list).
Update is not available in current python-novaplugin.
> Add flavor

- cinder_plugin/volume.py
- glance_plugin/image.py
- keystone_plugin/project.py
- keystone_plugin/tests/test_project.py
- keystone_plugin/tests/test_user.py
- keystone_plugin/user.py
- neutron_plugin/floatingip.py
- neutron_plugin/network.py
- neutron_plugin/port.py
- neutron_plugin/router.py
- neutron_plugin/security_group.py
- neutron_plugin/subnet.py
- nova_plugin/flavor.py
- nova_plugin/keypair.py
- nova_plugin/server.py
- nova_plugin/server_group.py
- nova_plugin/tests/test_flavor.py
- openstack_plugin_common/__init__.py
- plugin.yaml
Add list to all resources plus small refactor to use common functions.
> Add list to all

- README.md
> Fix Broken Link In ReadMe

- nova_plugin/server.py
There appears to be a problem with scale-in, introduced in https://github.com/cloudify-cosmo/cloudify-openstack-plugin/pull/239/commits/130a96213ae90787192fb4f7ff192517b79e95ba#diff-10781ebd5f4e8926f46e11fa0b6c239bR478. OpenStack returns a `409` if you attempt to stop a server that's already stopping. On particularly slow OpenStack rigs, powering off may take more than the 30s between retries of the `stop` operation. Thus, on such rigs, the openstack plugin may currently attempt to stop a server that's already stopping, and throw an exception.
This PR fixes this issue by explicitly checking for the `powering-off` status, and retrying 30s later if detected.
In the interests of expediency, I've not added any UT coverage. However, I have been able to reliably repro the issue above with …
> Skip stopping if server is currently powering off

- nova_plugin/host_aggregate.py
- nova_plugin/tests/test_host_aggregate.py
- plugin.yaml
Required for customer project. Tested in Cloudify Labs.
> Compute node add and remove operations for host aggregate

- nova_plugin/server.py
- nova_plugin/tests/test_server.py
In `connect_security_group()`, it currently tries to add the security group to the server for every non-matching security group in `server.list_security_group()`. The bug is only triggered when a server has more than one security group.
Trying to add the group again leads to 400 errors from Neutron like:
2018-08-16 09:29:46.702  CFY <clearwater> [establish] Task failed 'nova_plugin.server.connect_security_group' -> Invalid input for security_groups. Reason: Duplicate items in the list: '6ef1bf5b-6ebc-4995-a788-9e8de85fcb5a'.
Neutron server returns request_ids: ['req-b4cd4871-317c-4486-ac27-e638dae2ef29'] [status_code=400]
> Fix creating servers with multiple security groups

- CHANGELOG.txt
- nova_plugin/server.py
- nova_plugin/tests/test_server.py
- plugin.yaml
- setup.py
Hi, I'm not sure if I placed these new operation in a good place in plugin.yaml. If something is wrong, let me know, so I could fix this. Thanks, Jaroslaw.
> 2.11.2: added reboot operation to nova_plugin.server

- CHANGELOG.txt
- openstack_plugin/decorators.py
- openstack_plugin/tests/base.py
- openstack_plugin/tests/compute/test_server.py
- openstack_plugin/utils.py
- plugin.yaml
- setup.py
> fix heal remove id from kwargs

- README.md
- examples/manager/ZoneWithRecordSet.yaml
- openstack_plugin/resources/dns_service/record_set.py
- openstack_plugin/resources/dns_service/zone.py
- openstack_plugin/tests/dns_service/test_record_set.py
- openstack_plugin/tests/dns_service/test_zone.py
- openstack_sdk/resources/dns_service.py
- openstack_sdk/tests/base.py
- openstack_sdk/tests/dns_service/test_record_set.py
- openstack_sdk/tests/dns_service/test_zone.py
- plugin.yaml
- setup.py
Added Support for designate [ Zone , RecordSet ]
> CY-1637-Openstack-Designate-Support

- plugin.yaml
Fixed types description for record set Type
> CY-1637-Openstack-Designate-Support-Fix-Types-Description

- .circleci/config.yml
- CHANGELOG.txt
- examples/manager/User-Project-AssignExisting.yaml
- openstack_plugin/resources/identity/project.py
- plugin.yaml
- setup.py
Added a existing_resource_handler to Project to handle adding the users with their respective roles , and I included a small example
> CY-2324-Add-Users-To-Existing-Project

- .circleci/config.yml
- .circleci/test_examples.py
- CHANGELOG.txt
- constraints.txt
- plugin.yaml
- setup.py
- test-requirements.txt
> Replace wagon builder to py2py3 builder

- .circleci/config.yml
- .circleci/merge_docs.py
- .circleci/package_release.py
- CHANGELOG.txt
- constraints.txt
- plugin.yaml
- setup.py
- test-requirements.txt
- tox.ini
> Fix constraint for python2

- .circleci/test_examples.py
> remove bundle

- CHANGELOG.txt
- constraints.txt
- nova_plugin/server.py
- plugin.yaml
- test-requirements.txt
Simple fix for encoding for password generation on windows instance
> RD-711-Fix-Get-Generated-Password-Encoding

- .circleci/config.yml
Remove Integration Tests since we can't execute them at this time
> RD-711-Integration-Tests __NODOCS__

- .circleci/config.yml
> RD-711-Release __NODOCS__

- CHANGELOG.txt
- examples/local/flavor_with_extra_specs.yaml
- openstack_plugin/resources/compute/flavor.py
- openstack_plugin/tests/compute/test_flavor.py
- openstack_sdk/resources/compute.py
- plugin.yaml
- plugin_1_4.yaml
- v2_plugin.yaml
added extra specs support , and tenant access list -relevant if flavor is not public-
> CYBL-1527-Add-Flavor-ExtraSpecs-Access

- CHANGELOG.txt
- openstack_plugin/__version__.py
- openstack_plugin/utils.py
- plugin.yaml
- plugin_1_4.yaml
- plugin_1_5.yaml
- v2_plugin.yaml
handling of inspect changes for py3.11
> NE-23979-Handle-inspect-py311
